import enLocale from 'element-ui/lib/locale/lang/en'
const en = {
  common: {
    chinese: 'Chinese',
    login: 'Login',
    signUp: 'Register',
    station: 'Station',
    forgetPassword: 'Forgot password',
    resetPassword: 'Reset password',
    verifiedCode: 'Auth code',
    rememberPassword: 'Remember password',
    autoLogin: 'Auto login',
    inputUsernameTips: 'Input username',
    inputPasswordTips: 'Input password',
    errorPhoneNumber: 'Wrong phone number',
    inputCompletePassword: 'Password length not less than 6 digits',
    inputVerifyCodeTips: 'Please enter the verification code',
    inputCompleteCode: 'Verify code length not less than 6 digits',
    search: 'Search',
    filterCondition: 'Filter options',
    confirmCurrentPage: 'Confirm current page',
    emptyData: 'Empty data',
    mapAnalysis: 'Map',
    stationList: 'Station List',
    alarmList: 'Alarm List',
    systemSetting: 'System setting',
    groupUserSetting: 'Group user setting',
    carouselSetting: 'Carousel setting',
    carouselContent: 'Carousel content',
    customContent: 'Custom content',
    carouselInfo: 'Carousel info',
    alarmEvent: 'Alarm event',
    numbers2Show: 'Rows',
    templateShow: 'Template',
    sortField: 'Sort filed',
    cloudView: 'Cloud view',
    superAdministrator: 'Super administrator',

    basicInfo: 'Basic info',
    incomeInfo: 'Income info',
    electricityOfPeakValley: 'Peak valley electricity',
    peakElectricity: 'Peak electricity',
    valleyElectricity: 'Valley electricity',
    averageElectricity: 'Average electricity',

    address: 'Address',
    installedCapacity: 'Installed Capactiy',
    state: 'State',
    installedDate: 'Installed Date',
    chargeState: 'Charge State',
    directCurrentPower: 'DC Power',
    acPower: 'AC power',
    dcPower: 'DC power',
    runningStatus: 'Running status',
    deviceName: 'Device name',
    eventType: 'Event type',
    level: 'Level',
    deviceType: 'Device type',
    description: 'Description',
    confirmedMan: 'Confirmed man',
    operation: 'Operation',
    all: 'All',
    sleep: 'Sleep',
    normal: 'Normal',
    comError: 'Com. error',
    error: 'Error',
    info: 'Info',
    unknown: 'Unknown',
    comEvent: 'Com event',
    deviceEvent: 'Device event',
    videoEvent: 'Video event',
    camera: 'Camera',
    comId: 'Communication Id',
    manufacturer: 'Manufacturer',
    model: 'Model',
    time: 'Time',
    day: 'Day',
    week: 'Week',
    month: 'Month',
    year: 'Year',
    total: 'Total',
    updateTime: 'Update time',
    testPointName: 'Test point name',
    value: 'Value',
    unit: 'Unit',
    viewHistory: 'View history',
    recentOneWeek: 'Last week',
    recentOneMonth: 'Last month',
    recentThreeMonth: 'Last three month',
    selectTimeRange: 'Select time range',

    // 电站详情
    summary: 'Summary',
    device: 'Device',
    overview: 'Overview',
    treeAlike: 'Tree Alike',
    cardAlike: 'Card Alike',
    pcs: 'PCS',
    bms: 'BMS',
    video: 'Video',

    return: 'Back',
    failedLoading: 'Failed Loading',
    basicInfo: 'Basic Info',
    params: 'Params',
    income: 'Income',
    energy: 'Energy',
    power: 'Power',
    weather: 'Weather',
    alarm: 'Alarm',
    extraData: 'Extra Data',

    addSocialUnit: 'Add social unit',

    weather: 'Weather',
    incomeTrend: 'Income trend',
    owner: 'Owner',
    pcsBrands: 'PCS brands',
    batteryBrands: 'Battery brands',
    bmsBrands: 'BMS brands',
    capitalGains: 'Capital gains',
    currency: 'Currency',
    type: 'Type',
    timeRange: 'Time range',
    unit: 'Unit',
    price: 'Price',
    flatPrice: 'Flat price',
    highPeakPrice: 'High peak price',
    peakPrice: 'Peak price',
    valleyPrice: 'Valley price',
    season: 'Season',

    favorite: 'Favorite',
    history: 'History',
    sort: 'Sort',
    nearBy5km: 'Nearby 5km',
    nearBy10km: 'Nearby 10km',
    nearBy20km: 'Nearby 20km',
    nearBy50km: 'Nearby 50km',

    stationIdNullError: 'Station id is null, please contact with administrator',
    yes: 'Yes',
    no: 'No',
    addFilterCondition: 'Add filter opts',
    stationInfo: 'Station info',
    textCarousel: 'Text carousel',
    alarmCarousel: 'Alarm carousel',
    stationCarousel: 'Station carousel',

    kw: 'kW',
    kwh: 'kWh',
    chargePrice: 'Charge price',
    dischargePrice: 'Discharge price',
    runningInfo: 'Running info',
    charge: 'Charge',
    discharge: 'Discharge',
    envTemperature: 'Env temperature',
    socialUnitManagement: 'Social unit management',
    userRightsManagement: 'User rights management',
    addStation: 'Add station',
    workOrderManagement: 'Work order management',
    viewAlarmDetailsTip: 'View alarm details',
    addNewWorkOrderTip: 'Add work order',
    sendWorkOrder: 'Send',
    ok: 'Ok',
    cancel: 'Cancel',
    unvalidStationId: 'Unvalid station id',
    single: 'Single',
    multiple: 'Multiple',
    name: 'Name',
    seriesNum: 'Series number',
    confirm: 'Confirm',
    more: 'More',
    warning: 'Warning',
    warning2: 'Warning',
    unSavedTips: 'The data was not saved, are you sure to leave?',
    unrecoverabelTips: "This operation is unrecoverable, are you sure to delete?",

    registerSuccessfully: 'Register successfully',
    resetPasswordSuccessfully: 'Reset password successfully',

    custom: 'Custom',
    realTimeMonitoring: "RT monitoring",
    socialUnitDetails: 'Social unit details',
    hazardManagement: "Hazard management",
    operationManagement: 'Ops management',
    analysisDiagnosis: 'Analysis diagnosis',
    taskManagement: 'Task management',
    inspectionPlan: 'Inspection plan',
    workOrderDetails: 'Work order details',
    unsavedTips: 'The info was unsaved, are you sure to leave?',

    workOrderCount: 'Work order count',
    click2PlayPauseAudio: 'Click to play or pause audio',
    click2PlayAudio: 'Click to play audio',
    click2PauseAudio: 'Click to pause audio',
    enterpriseUserSetting: 'Enterprise user setting',
  },
  cloudView: {
    todo: 'Todo',
    doing: 'Doing',
    searchPlaceholder: 'Please input social unit name or address',
    basicInfo: 'Basic info',
    deviceCounts: 'Device counts',
    socialUnitCouts: 'Social unit couts',
    home: "Home",
    productName: "HuaJE Electrical Smart Safety System",
    exit: "Exit",

    alarmInfo: 'Alarm info',
    count: 'Count',
    name: 'Name',
    totalCounts: 'Total counts',
    normal: "Normal",
    offline: "Offline",
    alarm: "Alarm",
    error: "Error",
    hazard: 'Hazard',
    industry: "Industry",
    socialUnitStatus: "Social unit status",
    personResponsible: "Person responsible",
    hazardCauseStatistics: 'Hazard cause statistics',
    hazardAreaStatistics: 'Hazard area statistics',
    hazardIndustryStatistics: "Hazard industry statistics",
    hazardLevelStatistics: 'Hazard level statistics',
    hazardList: "Hazard list",
    updateTime: "Update time",
    socialUnit: "Social unit",
    deviceName: "Device name",
    hazardType: "Hazard type",
    hazardDesc: "Hazard desc",
    deviceStatus: 'Device status',
    currentTask: 'Current task',
    recentThirtyDaysTrend: "Recent thirty days trend",
    currentMonthHazard: "Current month hazard",
    lastMonthHazard: "Last month hazard",
    samePeriodLastYearHazard: "Same period last year hazard",
    relativeMonthGrowth: 'Relative month growth',
    relativeYearGrowth: 'Relative year growth',
    disposeOfHazard: "Dispose of hazard",
    click2ShowBox: 'Click to show box',
    click2HideBox: 'Click to hide box',
    hazardCountTitle: 'Hazard counts',

    todayChargeDischargeTrend: 'Today charge and discharge trend',
    lastFifteenDaysChargeDischargeTrend: 'Charge and discharge trend of last fifteen days',
    lastOneMonthIncomeTrend: 'Income trend of last one month',
    lastYearChargeDischargeTrend: 'Charge and discharge trend of last one year',

    calm: "Calm",
    lightAir: "Light air",
    slightBreeze: "Slight breeze",
    breeze: "Breeze",
    gentleBreeze: "Gentle breeze",
    freshBreeze: "Fresh breeze",
    strongWind: "Strong wind",
    highWind: "High wind",
    freshGale: "Fresh gale",
    blustery: "Blustery",
    wholeGale: "Whole gale",
    violentStrom: "Violent storm",
    level1Hurricane: "Level 1 Hurricane",
    level2Hurricane: "Level 2 Hurricane",
    level3SevereTyphoon: "Level 3 Hurricane", // severe typhoon
    level3SuperTyphoon: "Level 4 Hurricane", // super typhoon
    level4SuperTyphoon: "Level 5 Hurricane",
    level5SuperTyphoon: "Level 6 Hurricane",
  },

  login: {
    phoneNumber: 'Phone number',
    msgCode: 'Message code',
    password: 'Password',
    confirmPwd: 'Confirm password',
    name: 'Name',
    verifiedCode: 'Auth code',
    submit: 'Submit',
    reset: 'Reset',
    newPassword: 'New password',
    confirmNewPwd: 'Confirm new password',
    linkExchange: 'Link exchange',
    telephone: 'Telephone',
    email: 'Email',
    address: 'Address',
    hjCopyright: '©2017 Shenzhen Huajie Electrical Technology Co.,Ltd. Recorded number',
  },
  userAccount: {
    nickname: 'Nickname',
    userManagement: 'User management',
    loginName: 'Login name',
    telephone: 'Telephone',
    verifiedCode: 'Auth code',
    email: 'Email',
    credentialsType: 'Credentials type',
    selectCredentialsType: 'Select credentials type',
    credentialsNumber: 'Credentials number',
    getVerifyCode: 'Get auth code',
    save: 'Save',
    modifyPassword: 'Modify password',
    originalPwd: 'Original password',
    newPwd: 'New password',
    confirmNewPwd: 'Confirm new password',
    edit: 'Modify',
    inputNickname: 'Input nickname',
    inputPhoneNumber: 'Input phone number',
    errorPhoneNumber: 'Error phone number',
    phoneNumberNotChanged: 'Phone number unchanged',
    inputEmail: 'Please input e-mail',
    errorEmail: 'Error e-mail',
    failed2GetMsgCode: 'Failed to get message code',
    identityCard: "Identity card",
    drivingLicense: "Driving license",
    passport: "Passport",
    inputOriginalPwd: 'Please input original password',
    inputCharLenLimit: 'Six characters at least and fifteen characters at most',
    inputLoginName: 'Please input login name',
    noAllNumberAtLoginName: 'No all numbers in login name',
    noSpaceAtLoginName: 'No space in login name',

    inputNewPwd: 'Please input new password',
    inputNewPwdAgain: 'Please input new password again',
    errorNotSamePwd: 'Not the same password, try again',
    inputMsgCode: 'Please input message code',
    clickRightBtn2GetMsgCode: 'Please send the message code first',
    modifyPasswordTips: 'Notice: You need to sign in again after password was modified',
    errorCredentialsNumber: 'Credential number error',
    modifiedPwdSuccess: 'Password was modified',
    failed2ModifiedPwd: 'Failed to modified password',
    inputMailAddr: "Please input mail address",
    inputCorrectMail: "Please input correct mail",
    inputCredentialsNumber: 'Please input credentials number',
    saveSuccessfully: 'Save successfully',
    failedToSave: 'Failed to save',
    newPwdCannotEq2OldPwd: 'New password can not be equal to old password'
  },
  workOrderManagement: {
    handledByMe: 'Handled by me',
    createdByMe: 'Sended by me',
    keyword: 'Keyword',
    createdDate: 'Created date',
    toBeReceived: 'Assigned',
    processing: 'Handling',
    completed: 'Completed',
    closed: 'Closed',
    close: 'Close',
    finish: 'Finish',
    assigned: 'Assigned',
    receive: 'Receive',
    received: 'Received',
    resolved: 'Resolved',
    title: 'Title',
    currentWorkingMan: 'Current worker',
    relatedDevice: 'Related device',
    relatedStation: 'Related station',
    creator: 'Creator',
    updateTime: 'Update time',
    device: 'Device',
    description: 'Description',
    attachment: 'Attachment',
    comment: 'Comment',
    reject: 'Reject',
    addProcessingAdvice: 'Add adivce or comment',
    ok: 'Ok',
    cancel: 'Cancel',
    click2Upload: 'Click to upload',
    inputResolvedAdvice: 'Input adivce',
    advice: 'Advice',
    uploadImage: 'Upload image',
    imageFormatLimit: 'Jpg or png only',
    keywordPlaceholder: 'Please input work order title/station name/device name',
    stationNamePlaceHolder: 'Please input station name',
    receiveSuccess: 'Received successfully',
    addCommentSuccess: 'Added successfully',
    submitSuccess: 'Submit successfully',
    rejectedSuccess: 'Rejected successfully',
    approvedSuccess: 'Approved successfully',
    title: 'Title',
    inputWorkOrderTitle: 'Please input title',
    inputWorkOrderDescpt: 'Please input word order description',
    workOrderReceiver: 'Receiver',
    inputUserNameOrTel: 'Please input username/phone number',
    fullName: 'Name',
    telephone: 'Telephone',
    createNewWorkOrder: 'Create new work order',
    selectReceiver: 'Select receiver',
    addReceiver: 'Add receiver',
    imgFormatError: 'Error image format',

    viewDetails: 'View details',
    foldUp: 'Fold up',
    myTodo: "My todo",
    doneByMe: "Done by me",
    assignedByMe: "Assigned by me",
    addSuccessfully: 'Add successfully',
    addWorkOrder: 'Add work order',
    addMaintenance: 'Add maintenance',
    addAdvice: "Add advice",
    addAttachment: 'Add attachment',
    isSendedOrder: "Sended",
    isDone: 'Done',
    sendOrder: "Send",
    details: "Details",
    executor: 'Executor',
    selectExecutor: 'Please select executor',
    advancedSearch: 'Advanced search',
    cancelAdvancedSearch: 'Cancel',

    workOrderNumber: 'Work order number',
    handler: 'Handler',
    contactDetails: 'Contact details',
    currenStatus: 'Curren status',
    originator: 'Originator',
    basicInfo: 'Basic info',
    relatedInfo: 'Related info',
    socialUnit: 'Social unit',
    address: 'Address',
    hazardDesc: 'Hazard desc',
    deviceName: 'Device name',
    devicePos: 'Device position',
    hazardLevel: 'Hazard level',
    workOrderFlow: 'WorkOrder flow',
    inspectionTitle: 'Inspection title',
    inspectionContent: 'Inspection content',
    inspectionStartTime: 'Inspection start time',
    inspectionEndTime: 'Inspection end time',
    inspectionResult: 'Inspection result',
    maintenanceReason: 'Maintenance reason',
    maintenanceType: 'Maintenance type',
    hazardWorkOrder: 'Hazard work order',
    maintenanceWorkOrder: 'Maintenance work order',
    addComement: 'Add comement',
    rejectOperation: 'Reject operation',
    handleWorkOrder: 'Handled result',
    completeWorkOrder: 'Completed result',
    relatedDesc: 'Related desc',
    relatedTime: 'Related time',
    relatedWorkOrder: 'Related work order',
    back2OrginWorkOrder: 'Back',
    removeInspectionPlanTips: 'This operation is non-recoverable,are you sure?',

    creator: "Creator",
    creationTime: "Creation time",
    startTime: "Start time",
    endTime: "End time",
    socialUnit: "Social unit",
    executor: "Executor",
    inspectionTitle: "Inspection title",
    inspectionDescription: "Inspection description",
    operation: "Operation",
    inspectionDate: "inspection date",
    createInspectionPlan: "Create inspection plan",
    searchTips: "Please input keyword to search",

    relatedType: "Source type"
  },
  hazardManagement: {
    hazardStatus: "Hazard status",
    hazardLevel: "Hazard level",
    hazardDesc: "Hazard desc",
    keywordSearch: "Keyword search",
    eventDate: "Event date",
    socialUnit: "Social unit",
    devicePos: "Device position",
    deviceName: "Device name",
    eventTime: "Event time",
    address: "Address",
    reportManually: "Report manually",
    cancelAdvancedSearch: "Advanced search",
    search: "Search",
    reportSuccessfully: 'Report successfully',
    filter: 'Filter',
    risk: 'Risk',
    maintenance: 'Maintenance',
    patrol: 'Patrol',
    searchKeyword: "Search keyword",
    dealer: 'Dealer',
    solutionDesc: 'Solution desc',
    solutionTime: 'Solution time',
    processing: 'Processing',
    completed: 'Completed',

    basicInfo: "Basic info",
    realTimeData: "Real time data",
    hazardHistoryChart: "Hazard history chart",
    deviceStatus: "Device status",
    personResponsible: "Person responsible",
    contactDetails: "Contact details",
    hazardType: "Hazard type",
    click2ShowHazardDetails: 'Click to show hazard details',
    alarmValue: 'Alarm value',
    deviceManagement: 'Device management',
    inputAdviceTips: 'Input advice',
    selectAdviceTips: 'Select advice',
    commonAdvice: 'Frequent advice',
    commonAdvice1: 'Has handled',
    commonAdvice2: 'Has eliminated',
    commonAdvice3: 'Mistake hazrd',
    commonAdviceTips: "Click tag to padding advice above",
    emptyImgData: 'No image',
    hazardRecord: 'Hazard record',
    foundTime: 'Found time'
  },
  realTimeMonitoring: {
    searchKeyword: 'Please input station name or address',
    more: 'More',
    socialUnit: "Social unit",
    address: "Address",
    deviceCount: "Device count",
    onlineCount: "Online count",
    offlineCount: "offline count",
    todoHazard: "Todo hazard",
    handlingHazard: "Handling hazard",
    completedHazard: 'Completed hazard',
    viewDetails: "View details",
    operation: "Operation",
    foldUp: "Fold up",
    currentHazardStatistics: 'Current hazard statistics',
    paramsName: "Params name",
    paramsValue: "Params value",
    warningStatus: "Warning status",
    alarmStatus: "Alarm status",
    realTimeData: "Realtime data",
    paramsChart: "Params chart",
    custom: "Custom",
    residualCurrent: 'Residual current',
    temperature: 'Temperature',
    current: 'Current',
    voltage: 'Voltage',
    activePower: 'Active power',
    basicInfo: "Basic info",
    deviceStatus: "Device status",
    hazardStatistics: "Hazard statistics",
    industry: "Industry",
    unitTelephone: "Unit telephone",
    buildingArea: "Building area",
    personResponsible: "Person responsible",
    contactDetails: "Contact details",
    hazardList: "Hazard list",
    totalEnergy: 'Total energy',
    aPhaseVoltage: 'A phase voltage',
    bPhaseVoltage: 'B phase voltage',
    cPhaseVoltage: 'C phase voltage',
    aPhaseCurrent: 'A phase current',
    bPhaseCurrent: 'B phase current',
    cPhaseCurrent: 'C phase current',
  },
  socialUnitManagement: {
    searchKeyword: 'Please input social unit name or address'
  },
  systemSetting: {
    socialUnitSetting: 'Social unit management',
    communicationSetting: 'Communication management',
    basicSetting: 'Basic setting',
    paramsSetting: 'Params setting',
    deviceManagement: 'Device management',
    cameraSetting: 'Camera management',
    save: 'Save',
    reset: 'Reset',
    hasChanged: 'Has changed',
    quickSearchCity: 'Quick search city',
    longitude: 'Longitude',
    latitude: 'Latitude',
    ok: 'Ok',
    cancel: 'Cancel',
    stationName: 'Social unit name',
    owner: 'Social unit owner',
    latLng: 'Latitude and longitude',
    area: 'Area',
    dtuSerialNum: 'Dtu registcode',
    kwUnit: 'kW',
    kwhUnit: 'kWh',
    China: 'China',
    touEnabled: 'Enable tou',
    touId: 'Tou',
    installedCompany: 'Installed company',
    installedDate: 'Installed date',
    addDtu: 'Add dtu',
    addDevice: 'Add device',
    dtuName: 'Dtu name',
    deviceName: 'Device name',
    deviceType: 'Device type',
    deviceBrand: 'Device brand',
    deviceModel: 'Device model',
    comId: 'Comm.Id',
    addSuccess: 'Add successfully',
    modifySuccess: 'Update successfully',
    manResponsible: 'Man responsible',

    ratedPowValueTooSmall: 'Rated power must greater than 0',
    batteryCapValueTooSmall: 'Battery capacity must greater than 0',
    more: 'More',
    foldUp: 'Fold up',
    inputName: "Please input name",
    inputSerialNum: "Please input serial number",
    inputLiveAddr: "Please input live address",
    inputChannelId: "Please input channel id",
    cameraName: "Name",
    seriesNum: "Regist code",
    liveAddr: "Live addr",
    channelId: "Channel id",
    uneditedTips: "Data unchanged",
    imageFormatLimit: 'jpg/png only',
    selectFile: 'Select file',
    pics: 'Upload picture',
    batteryBrandName: 'Battery brand name',
    linkedBms: 'Linked bms',
    passwordNullError: 'Password is required',
    passwordError: 'Password error',
    removeSocialUnitSuccessfully: 'Remove social unit successfully',
    removeDtuSuccessfully: 'Remove dtu successfully',
    removeDeviceSuccessfully: 'Remove device successfully',
    saveSuccessfully: 'Save successfully',
    add: "Add",
    delete: "Delete",
    searchStationKeyword: 'Please input social unit name or address',

    inputPwdTips: 'Please input password(6 characters at least)',
    belongGroup: 'User group belongs',
    createTime: 'Create time',
    removeSuccessfully: 'Delete successfully',
    warnig2: 'Warning',
    addProprietor: 'Add owner',
    defaultPwdTips: 'Default passoword is the last six numbers of your phone number',
    addOpsUser: 'Add ops user',
    inputUsrNameOrPhoneNum: 'Input username or phone number',
    userList: 'User list',
    confirmResetPassword: 'Please confirm reset password',

    userListInGroup: 'User list--Current user group',
    homePath: 'Home path',
    operation: 'Operation',
    userWhoCanView: 'User who can view',
    unknown: 'Unknown',
    name: 'Name',
    installedCapacity_abbr: 'Installed capacity',
    remark: 'Detailed address',
    belongGroup: 'User group belonged',
    viewableUsers: 'Who can see',
    cancelRemove: 'Cancel delete',
    specifiedOwner: 'Specified owner',
    addStationViewable: 'Add social unit under current user',
    reservedItem: 'Reserved item',
    installCompany: 'Installed company',
    administrator: 'Administrator',
    proprietor: 'Owner',
    opsMember: 'Operation and maintenance user',
    socialUnit: 'Social unit',
    user: 'User',
    inputStationNameAddr: 'Please input social unit name or address',
    search: 'Search',
    identifier: "Identifier",
    switchRole: 'Transform role',
    userGroup: 'User group',
    password: 'Password',
    inputPwd: 'Please input password',
    currentGroup: 'Current user group',
    showSubUsergroup: 'Show sub user group',
    addUserGroup: 'Add user group',
    excuting: 'Excuting...',
    confirmDeleteGroup: 'Confirm delete user group',
    deleteGroup: 'Delete user group',
    enterpriseUserGroup: 'Enterprise user group',
    telephone: "Telephone",
    loginName: 'Login name',
    nickname: 'Nickname',
    role: 'Role',
    usrGroupTypeCanNotBeNull: "User group type is required",
    usrNameCanNotBeNull: "Username is required",
    inputUserGroupName: "Please input user group name",
    userGroupName: "User group name",
    userGroupType: "User group type",
    selectUserGroupType: "Please Select user group type",
    inputLoginName: 'Please input login name',
    noAllNumberAtLoginName: 'No all numbers in login name',
    noSpaceAtLoginName: 'No space in login name',
    inputCharFormatTips: 'Chinese, number, underline, shortline',
    inputNickname: 'Please input nickname',
    assignRole: 'Assign role',
    roleList: 'RoleL list',
    selectedRole: 'Selected role',
    delete: 'Delete',
    add: 'Add',
    basicProperty: 'Basic property',
    selectAddr: 'Please select address',
    address: 'Address',
    inputAddr: 'Please input address',
    detailedAddr: 'Detailed address',
    inputDetailedAddr: 'Please input detailed address',
    createTime: 'Create time',
    inputCreateTime: 'Please input create time',
    editTime: 'Update time',
    inputEditTime: 'Please input update time',
    selectUserGroup: 'Please select user group',
    resetPassword: 'Reset password',
    canNotBeNull: 'Can not be null',
    errorType: 'Error type',
    modifySuccessfully: 'Update successfully',
    confirmEditedResult: 'Confirm or cancel update',
    tips: 'Tips',
    cancelledEdit: 'Cancel update',
    click2Edit: 'Click to update',
    confirmEdit: 'Confirm update',
    inputPhoneNum: 'Please input phone number',
    errorPhoneNum: 'Error phone number',
    addUser: 'Add user',
    confirmAdd: 'Confirm add',
    userAuthorityMng: 'User rights management',
    opsUserProperty: 'Ops user property',
    proprietorProperty: 'Owner property',
    userProperty: 'User property',
    backendOpsGroup: 'Back end ops user group',
    cannotRemoveRoot: 'Can not delete root node',
    inputUserNameOrTel: 'Please input username/phone number',
    editBelongGroup: "Update user group belonged",
    notVisibleForEndUserOrUserGroup: "Delete the viewable user group or owner of social unit",
    configViewableForUserOrUserGroup: "Setting the viewable user group or user of social unit",
    configUnviewableStation: "Setting unviewable social unit",
    removeMaintenanceStaffTips: 'You cannot sign in with this account again after deleting, are you sure?',
    configUnviewableStationTip: "Enable remove the social unit from curren user",
    configUnviewableStationForUserTip: "Enable the social unit unviewable to current user",
    deleteSocialUnitTips: 'Remove social unit from current user group, it cannot remove if current user group was the owner',
    socialUnitListCanView: 'Social unit list current user can view',
    mustOneRoleAtLeast: 'Must one role leave at least',
    townCodeErrorTips: 'The area info is null, you should select detailed area by yourself',

    addContactItemLimits: 'You can add 5 items at most'
  },
  yahooWeather: {
    'tornado': 'tornado',
    'tropical storm': 'tropical storm',
    'hurricane': 'hurricane',
    'severe thunderstorms': 'severe thunderstorms',
    'thunderstorms': 'thunderstorms',
    'mixed rain and snow': 'mixed rain and snow',
    'mixed rain and sleet': 'mixed rain and sleet',
    'mixed snow and sleet': 'mixed snow and sleet',
    'freezing drizzle': 'freezing drizzle',
    'drizzle': 'drizzle',
    'freezing rain': 'freezing rain',
    'showers': 'showers',
    'snow flurries': 'snow flurries',
    'light snow showers': 'light snow showers',
    'blowing snow': 'blowing snow',
    'snow': 'snow',
    'hail': 'hail',
    'sleet': 'sleet',
    'dust': 'dust',
    'foggy': 'foggy',
    'haze': 'haze',
    'smoky': 'smoky',
    'blustery': 'blustery',
    'windy': 'windy',
    'cold': 'cold',
    'cloudy': 'cloudy',
    'mostly cloudy (night)': 'mostly cloudy (night)',
    'mostly cloudy (day)': 'mostly cloudy (day)',
    'partly cloudy (night)': 'partly cloudy (night)',
    'partly cloudy (day)': 'partly cloudy (day)',
    'clear (night)': 'clear (night)',
    'sunny': 'sunny',
    'fair (night)': 'fair (night)',
    'fair (day)': 'fair (day)',
    'mixed rain and hail': 'mixed rain and hail',
    'hot': 'hot',
    'isolated thunderstorms': 'isolated thunderstorms',
    'scattered thunderstorms': 'scattered thunderstorms',
    'scattered showers': 'scattered showers',
    'heavy snow': 'heavy snow',
    'scattered snow showers': 'scattered snow showers',
    'partly cloudy': 'partly cloudy',
    'thundershowers': 'thundershowers',
    'snow showers': 'snow showers',
    'isolated thundershowers': 'isolated thundershowers',
    'not available': 'not available'
  },
  ...enLocale
};

export default en
